# Generated by Django 3.0.4 on 2020-03-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Single_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='пароль')),
            ],
        ),
    ]
